Nombre = input("Cual es tu nombre?")
Apellido = input("Cual es tu apellido?")
Carrera = input("Que carrera estudias?")
Asignatura = input("Que asignatura tienes?")
Sede = input("En que sede?")
Semestre = input("En que semestre estas?")
año = input("En que año estas?")
Ciudad = input("En que ciudad vives?")
edad = input("Cual es tu edad?")
print("hola " + Nombre,Apellido + "," + " tu estudias " + Carrera + " y tienes la asinatura de " + Asignatura + "," + " situada en la sede de " + Sede + "." + " estas en el " + Semestre + " del primer " + año + " y vives en " + Ciudad + " y tienes " + edad)